---
- name: blockinfile
  hosts: rh92-0
  tasks:
    - name: block
      blockinfile:
        dest: "/tmp/bbc.txt"
        insertafter: EOF
        marker: ""
        content: "abcdefghijlmnopqrstuvwxyz"
        create: true
