---
- name: collect hosts
  hosts: all
  become: true
  tasks:
    - name: create directory on controller node
      delegate_to: rh92-0  # コントローラーノードのホスト名を指定
      ansible.builtin.file:
        path: "/tmp/collected_files"
        state: directory
        mode: '0755'

    - name: fetch hosts file to controller node
      delegate_to: rh92-0
      ansible.builtin.fetch:
        src: "/etc/hosts"
        dest: "/tmp/collected_files/{{ inventory_hostname}}.txt"
        flat: yes

    - name: debug src file on remote hosts
      ansible.builtin.command:
        cmd: cat /etc/hosts
      register: remote_hosts_content
    - debug:
        var: remote_hosts_content.stdout
