---
- hosts: 192.168.1.6
  gather_facts: no

  tasks:
    - name: Check if ansible_password is set
      ansible.builtin.debug:
        msg: "ansible_password is {{ ansible_password | default('NOT SET') }}"

    - name: Debug ansible_user
      ansible.builtin.debug:
        msg: "ansible_user is {{ ansible_user | default('NOT SET') }}"

    - name: setting variables
      vars:
        ansible_become_user: "{{ ansible_user }}"
        ansible_become_password: "{{ ansible_password }}"

      debug:
        msg: "{{ ansible_become_user }}"
