---
- hosts: 192.168.1.6
  gather_facts: no

  tasks:

    - name: Check current user (with become)
      ansible.windows.win_shell: whoami
      become: true
      register: become_user

    - name: Display become user
      ansible.builtin.debug:
        msg: "With become: {{ become_user.stdout }}"
