---
- hosts: 192.168.1.6
  gather_facts: no

  tasks:
    - name: Check current user (without become)
      ansible.windows.win_shell: whoami
      register: normal_user

    - name: Display normal user
      ansible.builtin.debug:
        msg: "Without become: {{ normal_user.stdout }}"

    - name: Check current user (with become)
      vars:
        ansible_become: true
        ansible_become_method: runas
        ansible_become_user: "{{ ansible_user }}"
        ansible_become_password: "{{ ansible_password }}"
        ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
      ansible.windows.win_shell: whoami
      become: true
      register: become_user

    - name: Display become user
      ansible.builtin.debug:
        msg: "With become: {{ become_user.stdout }}"
